apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: apprise-ingress
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://apprise.local.hohepa.dev
    gethomepage.dev/group: Infra
    gethomepage.dev/name: Apprise
    gethomepage.dev/icon: apprise.png
    gethomepage.dev/app: apprise
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`apprise.local.hohepa.dev`)
      kind: Rule
      services:
        - name: apprise
          port: 8000
  tls:
    secretName: local-hohepa-dev-tls
