apiVersion: v1
kind: Service
metadata:
  name: apprise
  namespace: services
spec:
  selector:
    app.kubernetes.io/name: apprise
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
