services:
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:2.0.10
    networks:
      - proxy
    ports:
      - 8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      TZ: NZ
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config:/config
      - ~:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${HOST}${SUBDOMAIN}local.hohepa.dev`)"
      - "traefik.http.routers.syncthing.entrypoints=https"
      - "traefik.http.routers.syncthing.tls=true"

networks:
  proxy:
    external: true
