# https://github.com/minio/minio/blob/master/helm/minio/values.yaml
image:
  tag: RELEASE.2025-09-07T16-13-09Z-cpuv1
mcImage:
  tag: RELEASE.2025-08-13T08-35-41Z-cpuv1

mode: standalone

rootUser: minio
rootPassword: miniominio

replicas: 1

persistence:
  existingClaim: minio-data-claim
resources:
  requests:
    memory: 256Mi
