apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-ingress
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://bazarr.local.hohepa.dev
    gethomepage.dev/group: Servarr
    gethomepage.dev/name: Bazarr
    gethomepage.dev/icon: bazarr.png
    gethomepage.dev/app: bazarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.local.hohepa.dev`)
      kind: Rule
      services:
        - name: bazarr
          port: 6767
  tls:
    secretName: local-hohepa-dev-tls
