apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home-assistant.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: home-assistant
          port: 8123
  tls:
    secretName: test-local-hohepa-dev-tls
