apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://home-assistant.test.local.hohepa.dev
    gethomepage.dev/group: Services
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/icon: home-assistant.png
    gethomepage.dev/app: home-assistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home-assistant.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: home-assistant
          port: 8123
  tls:
    secretName: test-local-hohepa-dev-tls
