services:
  homepage:
    container_name: homepage
    image: gethomepage/homepage:v1.5
    networks:
      - proxy
    ports:
      - 3000
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.${SUBDOMAIN}local.hohepa.dev
      TZ: NZ
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${SUBDOMAIN}local.hohepa.dev`)"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.tls=true"

networks:
  proxy:
    external: true
