apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: price-buddy-ingress
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`price-buddy.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: price-buddy
          port: 80
  tls:
    secretName: test-local-hohepa-dev-tls
