apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://homepage.local.hohepa.dev
    gethomepage.dev/group: Services
    gethomepage.dev/name: Homepage
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/app: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.local.hohepa.dev`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
  tls:
    secretName: local-hohepa-dev-tls
