---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: cnpg-system
spec:
  selector:
    app.kubernetes.io/name: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
