services:
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:2
    networks:
      - proxy
    ports:
      - 3001
    environment:
      TZ: NZ
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.${HOST}${SUBDOMAIN}local.hohepa.dev`)"
      - "traefik.http.routers.uptime.entrypoints=https"
      - "traefik.http.routers.uptime.tls=true"

networks:
  proxy:
    external: true
