apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebox-ingress
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://homebox.test.local.hohepa.dev
    gethomepage.dev/group: Services
    gethomepage.dev/name: Homebox
    gethomepage.dev/icon: homebox.png
    gethomepage.dev/app: homebox
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homebox.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: homebox
          port: 7745
  tls:
    secretName: test-local-hohepa-dev-tls
