apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-detection
  namespace: services
spec:
  selector:
    matchLabels:
      app: change-detection
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: change-detection
    spec:
      containers:
      - name: change-detection
        image: ghcr.io/dgtlmoon/changedetection.io:0.51
        env:
        - name: PLAYWRIGHT_DRIVER_URL
          value: ws://localhost:3000
        - name: BASE_URL
          value: https://change-detection.local.hohepa.dev
        - name: USE_X_SETTINGS
          value: "1"
        - name: HIDE_REFERER
          value: "true"
        - name: DISABLE_VERSION_CHECK
          value: "true"
        - name: TZ
          value: NZ
        ports:
          - containerPort: 5000
        volumeMounts:
        - mountPath: /datastore
          name: change-detection-data
      - name: playwright-chrome
        image: browserless/chrome:1.61-chrome-stable
        env:
          - name: SCREEN_WIDTH
            value: "1920"
          - name: SCREEN_HEIGHT
            value: "1024"
          - name: SCREEN_DEPTH
            value: "16"
          - name: ENABLE_DEBUGGER
            value: "false"
          - name: PREBOOT_CHROME
            value: "true"
          - name: CONNECTION_TIMEOUT
            value: "300000"
          - name: MAX_CONCURRENT_SESSIONS
            value: "10"
          - name: CHROME_REFRESH_TIME
            value: "600000"
          - name: DEFAULT_BLOCK_ADS
            value: "true"
          - name: DEFAULT_STEALTH
            value: "true"
          - name: DEFAULT_IGNORE_HTTPS_ERRORS
            value: "true"
        ports:
          - containerPort: 3000
      volumes:
      - name: change-detection-data
        persistentVolumeClaim:
          claimName:  change-detection-data-claim
