apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: change-detection-ingress
  namespace: services
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`change-detection.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: change-detection
          port: 5000
  tls:
    secretName: test-local-hohepa-dev-tls
