---
apiVersion: v1
kind: Service
metadata:
  name: change-detection
  namespace: services
spec:
  selector:
    app: change-detection
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
