apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingress
  namespace: services
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: https://radarr.test.local.hohepa.dev
    gethomepage.dev/group: Servarr
    gethomepage.dev/name: Radarr
    gethomepage.dev/icon: radarr.png
    gethomepage.dev/app: radarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.test.local.hohepa.dev`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
  tls:
    secretName: test-local-hohepa-dev-tls
